name: Snyk Security Check

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  snyk-sca-check:
    uses: getzoop/gha-workflows/.github/workflows/snyk_sca_check.yml@v6
    secrets:
      SNYK_TOKEN: ${{ secrets.SNK_TOKEN }}
  snyk-sast-check:
    uses: getzoop/gha-workflows/.github/workflows/snyk_sast_check.yml@v6
    secrets:
      SNYK_TOKEN: ${{ secrets.SNK_TOKEN }}